{% set version = "1.9.1" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3

build:
    number: 0
    skip: true    # [win]

requirements:
    build:
        - gcc     # [unix]
        - hdf5 1.8.18|1.8.18.*
        - cmake
    run:
        - libgcc  # [unix]
        - hdf5 1.8.18|1.8.18.*

test:
    commands:
        # Verify libraries.
        - test -f $PREFIX/lib/libflann_s.a                                        # [unix]
        - test -f $PREFIX/lib/libflann.dylib                                      # [osx]
        - test -f $PREFIX/lib/libflann.so                                         # [linux]
        - test -f $PREFIX/lib/libflann_cpp_s.a                                    # [unix]
        - test -f $PREFIX/lib/libflann_cpp.dylib                                  # [osx]
        - test -f $PREFIX/lib/libflann_cpp.so                                     # [linux]

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
    - dougalsutherland
