{% set version = "1.9.1" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: b23b5f4e71139faa3bcb39e6bbcc76967fbaf308c4ee9d4f5bfbeceaa76cc5d3
    patches:
        # CMake 3.11 breaks FLANN's existing src/cpp/CMakeLists.txt. See
        # https://github.com/mariusmuja/flann/issues/369 for more information.
        - src-cpp-fix-cmake-3.11-build.patch

build:
    number: 1

requirements:
    build:
        - gcc     # [unix]
        - {{ compiler('cxx') }}  # [win]
        - hdf5 1.8.18|1.8.18.*
        - cmake
    run:
        - libgcc  # [unix]
        - hdf5 1.8.18|1.8.18.*

test:
    commands:
        # Verify libraries.
        - test -d $PREFIX/include/flann                                           # [not win]
        - test -f $PREFIX/lib/libflann_s.a                                        # [unix]
        - test -f $PREFIX/lib/libflann.dylib                                      # [osx]
        - test -f $PREFIX/lib/libflann.so                                         # [linux]
        - test -f $PREFIX/lib/libflann_cpp_s.a                                    # [unix]
        - test -f $PREFIX/lib/libflann_cpp.dylib                                  # [osx]
        - test -f $PREFIX/lib/libflann_cpp.so                                     # [linux]
        - if not exist %LIBRARY_LIB%\\flann_cpp_s.lib exit 1                      # [win]
        - if not exist %LIBRARY_LIB%\\flann_s.lib exit 1                          # [win]
        - if not exist %LIBRARY_LIB%\\flann.lib exit 1                            # [win]
        - if not exist %LIBRARY_BIN%\\flann.dll exit 1                            # [win]
        - if not exist %LIBRARY_INC%\\flann exit 1                                # [win]

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
    - dougalsutherland
