{% set version = "1.8.5" %}

package:
    name: flann
    version: {{ version }}

source:
    fn: flann-{{ version }}.tar.gz
    url: https://github.com/mariusmuja/flann/archive/{{ version }}.tar.gz
    sha256: 59a9925dac0705b281496ae52b5dfd79d6b69316d37015e3d3b38c859bac4f2f

build:
    number: 1
    skip: true    # [win]

requirements:
    build:
        - gcc     # [unix]
        - hdf5 1.8.18|1.8.18.*
        - cmake
    run:
        - libgcc  # [unix]
        - hdf5 1.8.18|1.8.18.*

test:
    commands:
        # Verify libraries.
        - test -f $PREFIX/lib/libflann_s.a                                        # [unix]
        - test -f $PREFIX/lib/libflann.dylib                                      # [osx]
        - test -f $PREFIX/lib/libflann.so                                         # [linux]
        - test -f $PREFIX/lib/libflann_cpp_s.a                                    # [unix]
        - test -f $PREFIX/lib/libflann_cpp.dylib                                  # [osx]
        - test -f $PREFIX/lib/libflann_cpp.so                                     # [linux]

about:
    home: http://www.cs.ubc.ca/research/flann/
    license: BSD 3-Clause
    license_file: COPYING
    summary: "The Fast Library for Approximate Nearest Neighbors"

extra:
  recipe-maintainers:
    - jakevdp
    - jakirkham
