# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "sDdVrxxrzsydHh3c1QkpD6nI07EFO2zH2oA1SJjBYWoOiGBI7cxak+bKvJt8Fj01JDuutV+Fjcb3m68bmGlL5hmqRAju7AdyyEck17+iIAFEv2CvpnCX/KMgTfwGR3fdFHCbu0PhGNDiWpdBc6QzNBUMvYDkO0FS31hX+7YxDWLoUxzk1KqlVKeWTFH8bPfCw6e2i+UnbCmnRaRJWs0w8M+Akkg0ADiaZtJaXxT0J0PiNYola4PsRZMLQNP/iX5P5FwL4DNmuqSU0Ra2VJrF8xLtfghG07OX0ZJUkDLdfQOvbvyxSPhX3EpDVjUzQ/pcfjH0aNHZzzVQV/gA6PRLJUPwgyHJ0g/Nb9czQSYJPlIuEHz9obtMu6OnPsdw8NFuhrUStxUfiXMv0UNCOiHC/ipvKntfR8QBew0wkREsOZAVcaS8+nAMgr+eB0aHUOY8A0Rfs+VoxieexFSEJ8k0kYC651dqm7xeCTJZwvpMQCl8GdXvKpfdlGLe+2ILOoRQHHjNh2Sqpv8RKPBVrAJ2zTbyu3cZUXYv3Pm0wNmgwZbEEB1C4eh2d6wc8hmov4DkoQyyJct3G09SYOaQvcoNXeL1XFGtIWia0b0czzwSJuYpF8/mVCWMqugDezOaK4UXAJJ+lO7J1QjaZu3h87zBG+mzEcnrKpKNfz0mFcpz2AU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml