travis:
  secure:
    BINSTAR_TOKEN: l6Q+G9bqkGoXZR4FLmys08QbdYiVYCALXubla89nuphRaCylZXfSZFC3rNHEhiUa6e1e9CvExoV9sPkd7/LZFro5Xg0XctQcJsdYMjqaEsPzOseyzOog3y14gYrf6w6l+pe2q+a1D12DzykzTTSQyND0k1NM09Cyo48PqGrlEzsLapH+8sCzsYpgCtd272FFyluZkmG32uoYafZs0IHzfRPw+iFcLp9vshCJq/yjXLmUyhKo0WgEn3U7A+husMaqC98nHvRsVWqm0AiAd3SOA0WT6iXdKSFv1Y9zFA2YIuCcjNP4ecTQaQb7fsAIz1B9O8fNYPnn1V1G+TKuqABe/5j1LHQvZfJ+fLxW4o4d6XnrMfzB3cqJE3ojDe64XV5mTwJ/CzcN/+mq2lHCAbJe2LZ2ZDRvZWhjs2A4wVzYHcG61U0Fv6NxC3d1XzgJpoSZ+7mrpC2Ko72bHpEz50PydsXTEH+kZzxhqIy2ZHUfLVMTB5GiIpRpX75Hw1Mb2dvDv/Ve3zV4/T+VdGXAVjPKJ9y5TJiIe/3bXiZHicNrSb7u9PlluMW3c9hUp3FIM1N3raVBGReqNI4gvqIWHYzz+XiodM2D8nFCF0s0U9K3lYXDTeDGBlefHe+v8gleXIxbqQPu5mkgtVMrQ10hD1xFTAYriV3MdpzhInGYUIY2ZFs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
