travis:
  secure:
    BINSTAR_TOKEN: XsNBSTdSlhwP7iqCBRAqHWxrJfays+2I+c6dXrkhZpPB85Ql1UH7t3T3e/N7OkxQmwBMHV9qATh87JHxaOoDkNoelOe2BmK4nLEDQS+S1s0pfcNlCJ38e7TWmtRMBfTYDH9vB3T+vUPkPDSqDFHkmg4MJXv6RZN473fUfnIkFKXT26X7otj3OPa5a/dMkgA+jovx9yFL+lxdakyt5t/bAqI433H2zqYZhqODCTggALpPoHolcXe3t2wAZO4Z7QE7g7XIMDbwDfYtG+Ql2PRYP+yg8nFJsUYmhQTRY75fbusOGOurgejrF2E/zmh/LCeho6fvbEvaP7cjnhUWil9hZc0BJ2k475ZAY0IJ4PsEMU3QGm2aniwMbqleYujTX1UeyTr9MdjKX+5aSIUJrkh/5zpodM0WxHFgsSJnhPsRZtovJ3QyLG7LMbpxkd6N2Dqs93m+NnLjFjAgvFGRFbgaThy5YTtxcqeXFn0WcdVe4YDBa35UDtAKpicESSrcVSjSn7wizWzv2CmRRQNV/5HTvbSUWg0IkfsmOMjrc3gdXz4pmFK56zck110aTNkC2YGLGG/rkSe+XzZVYyiAvjJP0+k6wt9LslT/2RQeilTvaPY2Zh7DGWYtJ4SvcBpB5hEmPzOZHDMkyGbLQ62LbN+ACOzbxAR/pHTIu0X7MDFFvg8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
